Kitware/resonantgeo

devops/docker/assets/Dockerfile

This is a temporary work around, we will need to change how things get installed to support more recent versions of `girder-worker` and `girder-worker-utils`.
@aashish24 This should fix your build issue.

Pin girder-worker-utils to 0.7.1 to fix devops build

---

devops/docker/assets/Dockerfile
devops/docker/docker-compose.yml

Specify to use Pip 9, which is the version that is compatible with the code base;
Unify docker-compose service build arguments to avoid generating two docker image;

Two docker build fix

---

package.json

I'm going to publish a release to test external integration, and we don't want 1.0 yet.  :slightly_smiling_face:

Set to version 0.1.0 for publishing

---

.codecov.yml
examples/layout/src/MapView.vue
src/components/geojs/GeojsAnnotationLayer.vue
src/components/geojs/index.js
test/specs/GeojsAnnotationLayer.spec.js

The annotation layer currently provides the following:
* Contains a computed property to generate existing annotations as geojson.
* Toggles drawing mode for points, lines, rectangles, and polygons from props.
* Contains several props with `update` events that can be bound with the `.sync` modifier to simulate two way data binding.
There are also several initialization props that aren't reactive (for now):
* Initial annotations as geojson
* Whether annotations are editable
* Whether annotations are drawn with labels

Add an annotation layer component and related examples

---

examples/layout/src/MapView.vue
package.json
src/components/SidePanel.vue
src/components/SidePanelAction.vue
src/components/index.js
test/specs/SidePanel.spec.js
test/specs/SidePanelAction.spec.js

The original implementation was overly complicated and relied on constructing nested properties.  This provides a bit more flexibility in how the side panel is used and reduces the custom code in favor of standard vue behavior.
I'm also incrementing the version number to push a new release.

Side panel action component

---

examples/layout/src/MapView.vue
src/components/geojs/GeojsGeojsonLayer.vue
src/components/geojs/index.js
test/specs/GeojsGeojsonLayer.spec.js

This layer is similar to the annotation layer in that it is initialized
with a geojson object, but rendered features cannot be modified by the
layer itself.  The geojson prop provided to the layer is fully reactive
and will trigger a redraw for arbitrary changes to the geojson object
provided.
This component replaces all features on data changes; it is not designed
to be performant for large datasets.  Applications requiring frequent
redraw's and/or large numbers of features should modify the geojs
objects directly instead of relying on the built-in reactivity.

Add a Geojs geojson layer

---

examples/layout/src/MapView.vue
src/components/geojs/GeojsGeojsonLayer.vue
test/specs/GeojsGeojsonLayer.spec.js

This adds a `featureStyle` prop to the geojson layer type.  Users can
provide an independent style for each of the raw geojson types (point,
line, and polygon).  The style object is passed directly to the
`feature.style` method, so anything supported by geojs can be used here.
Note: If a function is provided as a style property, then you may need
to manually call the `draw()` method on the layer component when it
needs to be rerendered.

Add the ability to provide geojson styling

---

examples/layout/src/MapView.vue
src/components/geojs/GeojsWidgetLayer.vue
src/components/geojs/index.js
test/specs/GeojsWidgetLayer.spec.js

This adds a new `GeojsWidgetLayer` component for displaying arbitrary
content inside an element that pans with the map.  The logic in this
layer is primarily dedicated to setting the `left` and `top` css
properties of the widget parent when the map pans.
This default slot is appended to the layer's canvas on mount.  This
could cause problems when using with `v-if` directives depending on how
vue works.  I can make adjustments if there is ever a use case for this
behavior.
Props:
* position: The lat/lon position to center the element on
* size: The size of the component used to center the element correctly
* offset: Shifts the anchor point by the given offset in pixels
Example use case: Adding a text label to the right of -100 longitude 40
latitude.
```pug
geojs-widget-layer( …
```

Add a layer component to display arbitrary html

---

examples/layout/src/MapView.vue
src/bindWatchers.js
src/components/SidePanel.vue
src/components/geojs/GeojsAnnotationLayer.vue
src/components/geojs/GeojsGeojsonLayer.vue
src/components/geojs/GeojsHeatmapLayer.vue
src/components/geojs/GeojsTileLayer.vue
src/components/geojs/GeojsWidgetLayer.vue
src/mixins/geojsLayer.js
test/specs/GeojsLayerMixin.spec.js

This modifies the geojsLayer mixin to provide reactive zIndex and
opacity props to all layer types.  The opacity prop is now deduplicated
across all layers that previously supported the feature.
The zIndex prop is intend to provide a hook for developers to ensure the
layer order is consistent.  The previous behavior was that the z order
was determined by the order in which the layers were added to the map.
This causes issues for cases when the layer is added asynchronously into
the virtual DOM.

feat(geojs): add zIndex and opacity props to all layers

---

examples/layout/src/HeatmapView.vue
package-lock.json
package.json
src/bindWatchers.js
src/components/geojs/GeojsHeatmapLayer.vue
yarn.lock

This fixes a few small issues in the heatmap layer and example.
1. Use the "deep" flag when watching props to respond to changes in nested data.
2. Update the heatmap example to use zIndex.
3. Downgrade Vuetify to version 1.0.14 to fix resize bug in geojs's heatmap feature.  https://github.com/OpenGeoscience/geojs/issues/826

Listen to nested changes in heatmap data

---

src/components/geojs/GeojsAnnotationLayer.vue
test/specs/GeojsAnnotationLayer.spec.js

When draw mode is initialized geojs adds an annotation with no features
to the state.  This isn't usually what the watcher of the annotations
prop will be interested in.  Instead, this filters out all annotations
with no features from the exposed state on the Vue component.

Do not trigger state changes for empty annotations

---

src/components/SidePanel.vue

I thought there was a reason I added this originally, but I can't find anything that breaks.
Fixes #41

Remove z-index from the SidePanel

---

src/components/geojs/GeojsMapViewport.vue
test/specs/GeojsMapViewport.spec.js

This issue was caused by the Vuetify update.  It is an interaction
between bugs in vuetify and geojs, both of which have fixes in the
pipeline, but are not released.  This gets around the issue by ignoring
the spurious resize events.
Fixes #51

Only trigger a map resize when the canvas size changes

---

examples/layout/src/MapView.vue
src/components/geojs/GeojsWidgetLayer.vue
test/specs/GeojsWidgetLayer.spec.js

As pointed out by @matthewma7, the element centering can be done without knowing an explicit size using the css `transform` property.  The now unnecessary size prop has been removed.
Fixes #42

Remove the size prop from GeojsWidgetLayer

---

examples/girder/webpack.config.js
examples/layout/webpack.config.js
package.json

This change eliminates the need to prefix resonant geo modules with 'src/' (or webpack aliases).

Add "module" and "main" properties in the package.json

---

src/components/geojs/GeojsMapViewport.vue
test/specs/GeojsMapViewport.spec.js

This change allows users of the GeojsMapViewport to request a viewport
(map center, zoom, rotation) by mutating the `viewport` prop.
This implementation is not perfect, but should satisify most use cases
without major performance implications.  Due to constraints on the
viewport (via clamping), existing user interactions, transitions, and
numerical artifacts, the requested viewport might not be honored.  In
this case, the `update:viewport` event will *not* be retriggered with
the real value.  This is done to avoid infinite update loops that would
have to be handled by the user of the component.
If there are issues with this approach, we could add a new event that
fires synchronously with the "real" viewport that is not attached to a
prop.
Fixes #43

Make map viewport prop reactive

---

.circleci/config.yml
examples/girder/package-lock.json
examples/girder/src/main.js
examples/girder/webpack.config.js
examples/layout/package-lock.json
examples/layout/webpack.config.js
examples/layout/yarn.lock
package-lock.json
package.json
src/components/AppToolbar.vue
test/specs/SidePanel.spec.js
yarn.lock

This is needed for some features of the DataTable component added recently.  There is a possibility of some style related incompatibilities for downstream users.
* All element classes are now prefixed with `v-`.  Any global styles modifying vuetify elements will likely need changes to the selectors.
* I had to change how `vue` is aliased to ensure that it isn't duplicated in the bundle.  This may just be an artifact of how resonantgeo is symlinked into place for the builtin examples.

Update Vuetify to version 1.1.4

---

examples/girder/yarn.lock
examples/layout/yarn.lock
package-lock.json
package.json
yarn.lock

Unpinning will let downstream users to make further updates to vuetify without needing to modify
resonantgeo.

Update and unpin vuetify

---

src/rest.js

Constructors should only have an explicit return value in non-standard scenarios where they wish to return something other than `this`.

Prefer normal constructor semantics in Session

---

examples/layout/src/MapView.vue
src/components/geojs/GeojsColorLegendWidget.vue
src/components/geojs/index.js
test/specs/GeojsColorLegendWidget.spec.js

Add a GeojsColorLegendWidget that wraps GeoJS color legend widget. It  would be used as a child component of GeojsMapViewport.

feat(geojs): add GeojsColorLegendWidget component
